modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/SwanX1/fractal-skylands-tweaks/issues"

[[mods]]
  modId="fractalskylandstweaks"
  version="${file.jarVersion}"
  displayName="Fractal Skylands Tweaks"
  # See: https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
  updateJSONURL="https://cernavskis.dev/api/fractalskylandstweaks.json"
  displayURL="https://github.com/SwanX1/fractal-skylands-tweaks"
  #logoFile="examplemod.png"
  credits="SwanX1"
  authors="SwanX1"
  description='''
  Fractal Skylands Tweaks is a mod that adds features and tweaks to the Fractal Skylands modpack.
  Read more: https://github.com/SwanX1/fractal-skylands-tweaks/wiki
  '''

[[dependencies.fractalskylandstweaks]]
  modId="forge"
  mandatory=true
  versionRange="[36.2.20,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.fractalskylandstweaks]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.5,1.17)"
  ordering="NONE"
  side="BOTH"

# [[dependencies.fractalskylandstweaks]]
#   modId="tetra"
#   mandatory=true
#   versionRange="[3.20.0,)"
#   ordering="NONE"
#   side="BOTH"
